development:
  adapter: mysql
  encoding: utf8
  database: popefact
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: popefact-test
  username: root
  password: 
  host: localhost

